import { SimulationScenario, SimulationStrategy, FutureForkNode } from '../types/simulation';

export const demoScenario: SimulationScenario = {
  id: 'transport-crisis-2026',
  title: 'Future Transportation Crisis: Megacity Gridlock 2026–2050',
  titleTa: 'எதிர்கால போக்குவரத்து நெருக்கடி: பெருநகர நெரிசல் 2026–2050',
  tagline: 'Simulating induced traffic demand, public transit investment, air quality, and municipal health stress.',
  taglineTa: 'போக்குவரத்து நெரிசல், பொதுப் போக்குவரத்து முதலீடு, காற்றுத் தரம் மற்றும் மருத்துவ சுமையை உருவகப்படுத்துதல்.',
  description:
    'A metropolitan region of 1.0M expanding to 1.8M by 2050. Without strategic intervention, vehicle congestion causes catastrophic economic lost-hours, spikes respiratory ailments, and exhausts the municipal budget.',
  descriptionTa:
    '10 லட்சம் மக்கள் தொகை கொண்ட பெருநகரம் 2050க்குள் 18 லட்சமாக உயர்கிறது. தகுந்த கொள்கை முடிவுகள் இன்றி ஏற்படும் நெரிசல், பொருளாதார இழப்பு மற்றும் சுவாச நோய்களை அதிகரிக்கிறது.',
  category: 'Urban & Transport',
  timeHorizon: {
    startYear: 2026,
    endYear: 2050,
    intervals: [2026, 2030, 2035, 2040, 2050],
  },
  entities: [
    {
      id: 'ent-population',
      name: 'Demographic Scale',
      nameTa: 'மக்கள் தொகை அளவு',
      category: 'Demographics',
      description: 'Active urban and suburban commuter population dynamics.',
      descriptionTa: 'நகர மற்றும் புறநகர் பயணிகளின் மக்கள் தொகை இயக்கவியல்.',
      iconName: 'Users',
      color: '#38bdf8',
    },
    {
      id: 'ent-mobility',
      name: 'Mobility & Congestion',
      nameTa: 'போக்குவரத்து நெரிசல்',
      category: 'Infrastructure',
      description: 'Road density, travel delay times, and daily trip volumes.',
      descriptionTa: 'சாலை அடர்த்தி, பயண தாமத நேரம் மற்றும் தினசரி பயண அளவு.',
      iconName: 'Car',
      color: '#f59e0b',
    },
    {
      id: 'ent-transit',
      name: 'Public Mass Transit',
      nameTa: 'பொதுப் போக்குவரத்து',
      category: 'Infrastructure',
      description: 'Metrorail, light electric transit, and bus frequency throughput.',
      descriptionTa: 'மெட்ரோ ரயில், மின்திரை பேருந்து மற்றும் பயணக் கொள்ளளவு.',
      iconName: 'Train',
      color: '#10b981',
    },
    {
      id: 'ent-environment',
      name: 'Ecological & Air Quality',
      nameTa: 'சுற்றுச்சூழல் & காற்றுத் தரம்',
      category: 'Environment',
      description: 'Particulate emission (PM2.5), smog indices, and greenhouse discharge.',
      descriptionTa: 'நுண்துகள் மாசு (PM2.5), நச்சுப்புகை மற்றும் காற்று குறியீடு.',
      iconName: 'Leaf',
      color: '#06b6d4',
    },
    {
      id: 'ent-health-budget',
      name: 'Healthcare & Municipal Budget',
      nameTa: 'மருத்துவ சுமை & நிதிநிலை',
      category: 'Economy',
      description: 'Respiratory disease burden and infrastructure capital expenditures.',
      descriptionTa: 'சுவாச நோய்கள் காரணமாக ஏற்படும் மருத்துவ செலவு மற்றும் நிதி அழுத்தம்.',
      iconName: 'Activity',
      color: '#ec4899',
    },
  ],
  variables: [
    {
      id: 'var-pop',
      entityId: 'ent-population',
      name: 'Urban Population',
      nameTa: 'நகர மக்கள் தொகை',
      category: 'Demographics',
      value: 1.0,
      baselineValue: 1.0,
      unit: 'Million',
      min: 0.8,
      max: 2.5,
      step: 0.05,
      elasticity: 0.85,
      description: 'Total active resident population across metropolitan borders.',
      descriptionTa: 'பெருநகர எல்லைக்குட்பட்ட மொத்த குடியிருப்பாளர்கள் எண்ணிக்கை.',
      provenance: 'REAL DATA',
    },
    {
      id: 'var-veh-density',
      entityId: 'ent-mobility',
      name: 'Vehicle Density Ratio',
      nameTa: 'வாகன அடர்த்தி விகிதம்',
      category: 'Infrastructure',
      value: 520,
      baselineValue: 520,
      unit: 'cars / 1k pop',
      min: 200,
      max: 850,
      step: 10,
      elasticity: 0.72,
      description: 'Registered motor vehicles per one thousand residents.',
      descriptionTa: 'ஆயிரம் மக்களுக்கு இருக்கும் பதிவு செய்யப்பட்ட வாகனங்கள்.',
      provenance: 'REAL DATA',
    },
    {
      id: 'var-transit-cap',
      entityId: 'ent-transit',
      name: 'Public Transit Capacity',
      nameTa: 'பொதுப் போக்குவரத்து திறன்',
      category: 'Infrastructure',
      value: 320,
      baselineValue: 320,
      unit: 'k daily trips',
      min: 100,
      max: 1200,
      step: 20,
      elasticity: -0.68,
      description: 'Capacity of metro, BRT and high-frequency electric bus arteries.',
      descriptionTa: 'மெட்ரோ மற்றும் அதிவேக பேருந்துகளின் தினசரி பயண திறன்.',
      provenance: 'USER INPUT',
    },
    {
      id: 'var-highway-expansion',
      entityId: 'ent-mobility',
      name: 'Highway Lane Addition',
      nameTa: 'நெடுஞ்சாலை விரிவாக்கம்',
      category: 'Infrastructure',
      value: 15,
      baselineValue: 15,
      unit: 'lane-km / yr',
      min: 0,
      max: 80,
      step: 5,
      elasticity: 0.45,
      description: 'New vehicular asphalt lanes added annually (induces further traffic).',
      descriptionTa: 'ஆண்டுதோறும் புதிதாக சேர்க்கப்படும் சாலை பாதைகள் (கூடுதல் நெரிசலை தூண்டும்).',
      provenance: 'USER INPUT',
    },
    {
      id: 'var-ev-adoption',
      entityId: 'ent-environment',
      name: 'Clean Fleet Transition (EV)',
      nameTa: 'மின்னணு வாகன பயன்பாடு',
      category: 'Technology',
      value: 14,
      baselineValue: 14,
      unit: '% of fleet',
      min: 5,
      max: 95,
      step: 1,
      elasticity: -0.65,
      description: 'Percentage of electric and zero-emission vehicles in circulation.',
      descriptionTa: 'நகரத்தில் இயங்கும் மின்சார மற்றும் மாசு இல்லாத வாகனங்களின் சதவீதம்.',
      provenance: 'SIMULATED DATA',
    },
    {
      id: 'var-commute-delay',
      entityId: 'ent-mobility',
      name: 'Average Commute Delay',
      nameTa: 'சராசரி பயண தாமதம்',
      category: 'Infrastructure',
      value: 46,
      baselineValue: 46,
      unit: 'min / trip',
      min: 15,
      max: 120,
      step: 1,
      elasticity: 0.9,
      description: 'Peak morning and evening congestion delay beyond free-flow speed.',
      descriptionTa: 'காலை மற்றும் மாலை நேர நெரிசலால் ஏற்படும் கூடுதல் தாமத நேரம்.',
      provenance: 'SIMULATED DATA',
    },
    {
      id: 'var-aqi',
      entityId: 'ent-environment',
      name: 'Urban Air Quality Index',
      nameTa: 'காற்றுத் தரக் குறியீடு (AQI)',
      category: 'Environment',
      value: 138,
      baselineValue: 138,
      unit: 'AQI index',
      min: 25,
      max: 350,
      step: 2,
      elasticity: 0.78,
      description: 'Annual median PM2.5 and NOx ambient exposure level.',
      descriptionTa: 'ஆண்டு சராசரி நுண்துகள் மற்றும் நச்சுப்புகை காற்று மாசுபாடு அளவு.',
      provenance: 'SIMULATED DATA',
    },
    {
      id: 'var-health-cost',
      entityId: 'ent-health-budget',
      name: 'Respiratory Healthcare Burden',
      nameTa: 'சுவாச மருத்துவ செலவு சுமை',
      category: 'Economy',
      value: 410,
      baselineValue: 410,
      unit: '$M / year',
      min: 100,
      max: 1500,
      step: 10,
      elasticity: 0.88,
      description: 'Direct municipal and family healthcare expense tied to vehicular smog.',
      descriptionTa: 'வாகனப் புகையினால் ஏற்படும் சுவாச நோய்களுக்கான மருத்துவ செலவு.',
      provenance: 'AI-GENERATED ASSUMPTION',
    },
  ],
  dependencies: [
    {
      source: 'var-pop',
      target: 'var-veh-density',
      strength: 0.65,
      latencyYears: 1,
      description: 'Population density growth escalates overall personal automobile registrations.',
      descriptionTa: 'மக்கள் தொகை பெருக்கம் வாகனங்களின் எண்ணிக்கையை நேரடியாக உயர்த்துகிறது.',
    },
    {
      source: 'var-veh-density',
      target: 'var-commute-delay',
      strength: 0.84,
      latencyYears: 0,
      description: 'Higher vehicular density directly saturates chokepoints and bottlenecks.',
      descriptionTa: 'அதிக வாகனங்கள் முக்கியமான சாலை சந்திப்புகளில் தீவிர நெரிசலை உருவாக்குகின்றன.',
    },
    {
      source: 'var-transit-cap',
      target: 'var-commute-delay',
      strength: -0.74,
      latencyYears: 1,
      description: 'High transit capacity absorbs commuters off highways and relieves gridlock.',
      descriptionTa: 'பொதுப் போக்குவரத்து திறன் பயணிகளை சாலைகளில் இருந்து மெட்ரோவிற்கு மாற்றுகிறது.',
    },
    {
      source: 'var-highway-expansion',
      target: 'var-veh-density',
      strength: 0.42,
      latencyYears: 3,
      description: 'Induced Demand: Adding highway lanes temporarily speeds flow but induces more drivers.',
      descriptionTa: 'தூண்டப்பட்ட தேவை: அதிக சாலைகள் அமைப்பது தற்காலிகமாக உதவும், பின் கூடுதல் வாகனங்களை ஈர்க்கும்.',
    },
    {
      source: 'var-commute-delay',
      target: 'var-aqi',
      strength: 0.71,
      latencyYears: 0,
      description: 'Idling engines in stop-and-go gridlock emit 3x more micro-particulates per mile.',
      descriptionTa: 'நெரிசலில் நிற்கும் வாகனங்கள் மூன்று மடங்கு அதிக நச்சுப் புகையை வெளியிடுகின்றன.',
    },
    {
      source: 'var-ev-adoption',
      target: 'var-aqi',
      strength: -0.66,
      latencyYears: 0,
      description: 'Fleet electrification eliminates tailpipe combustion, reducing city-center smog.',
      descriptionTa: 'மின்சார வாகனங்கள் நேரடியாக வெளியேறும் நச்சுப் புகையை முற்றிலுமாக தவிர்க்கின்றன.',
    },
    {
      source: 'var-aqi',
      target: 'var-health-cost',
      strength: 0.88,
      latencyYears: 2,
      description: 'Sustained exposure to poor AQI triggers asthma, cardiovascular emergencies, and hospitalizations.',
      descriptionTa: 'தொடர்ச்சியான காற்று மாசுபாடு ஆஸ்துமா மற்றும் இருதய நோய்களுக்கான மருத்துவ செலவை கூட்டுகிறது.',
    },
  ],
  constraints: [
    {
      id: 'con-1',
      text: 'Municipal Annual Infrastructure Budget cannot exceed $1.2B / year.',
      textTa: 'நகர உள்கட்டமைப்பு பட்ஜெட் ஆண்டுக்கு $1.2 பில்லியனை தாண்டக்கூடாது.',
      status: 'satisfied',
    },
    {
      id: 'con-2',
      text: 'Peak commute delay must remain under 60 minutes to prevent economic flight.',
      textTa: 'பொருளாதார இழப்பைத் தவிர்க்க சராசரி பயண நேரம் 60 நிமிடங்களுக்குள் இருக்க வேண்டும்.',
      status: 'warning',
    },
    {
      id: 'con-3',
      text: 'Ambient AQI must not breach hazardous threshold (> 200).',
      textTa: 'காற்றுத் தரம் அபாயகரமான அளவை (>200) கடக்கக் கூடாது.',
      status: 'satisfied',
    },
  ],
  objectives: [
    {
      id: 'obj-1',
      targetMetric: 'Average Commute Delay',
      targetMetricTa: 'சராசரி பயண தாமதம்',
      targetValue: 30,
      direction: 'minimize',
      unit: 'min',
    },
    {
      id: 'obj-2',
      targetMetric: 'Urban Air Quality Index',
      targetMetricTa: 'காற்றுத் தரக் குறியீடு',
      targetValue: 60,
      direction: 'minimize',
      unit: 'AQI',
    },
    {
      id: 'obj-3',
      targetMetric: 'Public Transit Share',
      targetMetricTa: 'பொதுப் போக்குவரத்து பயன்பாடு',
      targetValue: 65,
      direction: 'maximize',
      unit: '%',
    },
  ],
  risks: [
    {
      id: 'risk-induced-demand',
      name: 'Induced Demand Paradox Trap',
      nameTa: 'தூண்டப்பட்ட தேவை பொறி',
      severity: 'high',
      thresholdTrigger: 'Highway expansion > 35 lane-km while Transit < 400k trips',
      thresholdTriggerTa: 'நெடுஞ்சாலை விரிவாக்கம் > 35 கிமீ மற்றும் பொதுப் போக்குவரத்து < 400k',
      mitigation: 'Implement variable congestion pricing and dedicate lanes to Bus Rapid Transit.',
      mitigationTa: 'நெரிசல் கட்டணம் விதித்து, பேருந்துகளுக்கு தனிப் பாதைகளை ஒதுக்குங்கள்.',
      probability: 78,
      impactScore: 8.5,
    },
    {
      id: 'risk-health-insolvency',
      name: 'Smog-Induced Healthcare Deficit',
      nameTa: 'மாசுபாட்டினால் விளையும் மருத்துவ நிதி பற்றாக்குறை',
      severity: 'critical',
      thresholdTrigger: 'AQI > 175 for 3 consecutive simulation cycles',
      thresholdTriggerTa: 'தொடர்ந்து 3 சுழற்சிகளுக்கு AQI > 175 ஆக நீடித்தால்',
      mitigation: 'Aggressive low-emission zones (LEZ) and electric bus fleet subsidies.',
      mitigationTa: 'குறைந்த உமிழ்வு மண்டலங்கள் மற்றும் மின்சார பேருந்துகளுக்கு மானியம்.',
      probability: 64,
      impactScore: 9.2,
    },
    {
      id: 'risk-budget-overrun',
      name: 'Subterranean Rail Cost Escalation',
      nameTa: 'சுரங்க மெட்ரோ ரயில் செலவு அதிகரிப்பு',
      severity: 'medium',
      thresholdTrigger: 'Transit expansion capital expenditure > $5.0B in single decade',
      thresholdTriggerTa: 'மெட்ரோ ரயில் செலவு பத்தாண்டில் $5.0B ஐ தாண்டினால்',
      mitigation: 'Prioritize surface at-grade electric light-rail and smart automated bus lanes.',
      mitigationTa: 'மேற்பரப்பு நவீன மின்சார ரயில் மற்றும் தானியங்கி பேருந்து பாதைகளுக்கு முன்னுரிமை.',
      probability: 45,
      impactScore: 6.8,
    },
  ],
  assumptions: [
    {
      id: 'as-1',
      statement: 'Population growth maintains a 2.4% compound annual rate driven by knowledge-industry immigration.',
      statementTa: 'மக்கள் தொகை ஆண்டுக்கு 2.4% வீதத்தில் தொழில் குடியேற்றத்தால் வளரும் என கணிக்கப்படுகிறது.',
      confidence: 85,
    },
    {
      id: 'as-2',
      statement: 'Electric vehicle battery parity achieved by 2028, accelerating private consumer adoption.',
      statementTa: '2028க்குள் மின்சார பேட்டரி விலை குறைந்து தனியார் வாகன பயன்பாடு அதிகரிக்கும்.',
      confidence: 80,
    },
    {
      id: 'as-3',
      statement: 'Autonomous ride-share vehicles will comprise 25% of micro-transit by 2038.',
      statementTa: '2038க்குள் தானியங்கி பகிரப்பட்ட வாகனங்கள் 25% வரை பயன்பாட்டில் வரும்.',
      confidence: 62,
    },
  ],
  createdAt: '2026-03-01T00:00:00.000Z',
  updatedAt: '2026-03-01T00:00:00.000Z',
};

export const demoStrategies: { strategyA: SimulationStrategy; strategyB: SimulationStrategy } = {
  strategyA: {
    id: 'strat-highways',
    name: 'Strategy A: Multi-Tier Highway & Expressway Expansion',
    nameTa: 'உத்தி A: அடுக்கு நெடுஞ்சாலை & மேம்பால விரிவாக்கம்',
    description: 'Construct 280km of elevated multi-tier expressways, widen arterial rings, and digitize toll gates.',
    descriptionTa: '280 கிமீ உயரமான மேம்பாலங்கள் அமைத்தல், சாலைகளை விரிவாக்குதல் மற்றும் டிஜிட்டல் சுங்கச்சாவடிகள்.',
    color: '#f59e0b',
    costBillions: 5.4,
    implementationYears: 6,
    actions: [
      {
        variableId: 'var-highway-expansion',
        deltaPercent: 120,
        description: 'Expand road asphalt additions from 15 to 33 lane-km/year.',
        descriptionTa: 'ஆண்டு சாலை விரிவாக்கத்தை 15 இலிருந்து 33 கிமீ வரை உயர்த்துதல்.',
      },
      {
        variableId: 'var-transit-cap',
        deltaPercent: 10,
        description: 'Minimal maintenance investment for existing transit lines.',
        descriptionTa: 'தற்போதைய பேருந்து பராமரிப்பிற்கு குறைந்தபட்ச நிதி.',
      },
    ],
    efficiencyScore: 54,
    riskLevel: 'High',
    longTermImpact: 'Marginal',
    resourceDemandScore: 78,
    goalAchievement: 42,
  },
  strategyB: {
    id: 'strat-transit-grid',
    name: 'Strategy B: Zero-Emission High-Capacity Transit & Micro-Mobility Grid',
    nameTa: 'உத்தி B: அதிவேக தூய பொதுப் போக்குவரத்து & மைக்ரோ-மொபிலிட்டி',
    description: 'Deploy 4 automated electric light-rail lines, dedicated Bus Rapid Transit (BRT) veins, and 180km protected active mobility lanes.',
    descriptionTa: '4 தானியங்கி மின்சார ரயில் பாதைகள், பிரத்யேக அதிவேக பேருந்து வழிகள் மற்றும் 180 கிமீ பாதுகாப்பான மிதிவண்டி பாதைகள்.',
    color: '#10b981',
    costBillions: 4.6,
    implementationYears: 5,
    actions: [
      {
        variableId: 'var-transit-cap',
        deltaPercent: 180,
        description: 'Triple high-frequency public transit throughput from 320k to 896k trips/day.',
        descriptionTa: 'பொதுப் போக்குவரத்து பயணத் திறனை 320k இலிருந்து 896k வரை மும்மடங்கு உயர்த்துதல்.',
      },
      {
        variableId: 'var-ev-adoption',
        deltaPercent: 85,
        description: 'Mandate municipal fleet electrification and subsidize commercial e-vans.',
        descriptionTa: 'அனைத்து நகராட்சி வாகனங்களையும் மின்சார மயமாக்குதல்.',
      },
      {
        variableId: 'var-highway-expansion',
        deltaPercent: -60,
        description: 'Repurpose outer vehicular lanes into dedicated high-capacity rapid transit corridors.',
        descriptionTa: 'சாலைப் பாதைகளை பேருந்து மற்றும் ரயில் வழித்தடங்களாக மாற்றுதல்.',
      },
    ],
    efficiencyScore: 89,
    riskLevel: 'Low',
    longTermImpact: 'Transformational',
    resourceDemandScore: 48,
    goalAchievement: 91,
  },
};

export const demoForkTree: FutureForkNode[] = [
  {
    id: 'fork-root-2026',
    parentId: null,
    year: 2026,
    title: 'Baseline Inception: 1.0M Population',
    titleTa: 'தொடக்க நிலை: 10 லட்சம் மக்கள் தொகை',
    branchName: 'Root Scenario',
    branchNameTa: 'முதன்மை காட்சி',
    strategyName: 'Status Quo',
    status: 'active',
    summary: 'Initial state with 46 min average commute delay and AQI 138.',
    summaryTa: 'தொடக்க நிலை: சராசரி பயண தாமதம் 46 நிமிடம் மற்றும் காற்று குறியீடு 138.',
    description: 'Initial state with 46 min average commute delay, 138 AQI, and $410M annual healthcare burden.',
    descriptionTa: 'தொடக்க நிலை: சராசரி பயண தாமதம் 46 நிமிடம், காற்று குறியீடு 138 மற்றும் ஆண்டுக்கு $410M மருத்துவ சுமை.',
    metrics: {
      delay: 46,
      aqi: 138,
      cost: 410,
      risk: 45,
      stress: 52,
    },
    kpis: {
      trafficCongestion: 52,
      pollutionAQI: 138,
      budgetHealth: 88,
      socialAcceptance: 70,
    },
    variableOverrides: {},
    children: ['fork-a-2035', 'fork-b-2035'],
  },
  {
    id: 'fork-a-2035',
    parentId: 'fork-root-2026',
    year: 2035,
    title: 'Branch A: Expressway Build-Out Failure (Induced Demand Trap)',
    titleTa: 'கிளை A: மேம்பால விரிவாக்கத் தோல்வி (தூண்டப்பட்ட நெரிசல்)',
    branchName: 'Highway Dominance',
    branchNameTa: 'நெடுஞ்சாலை ஆதிக்கம்',
    strategyName: 'Strategy A',
    status: 'divergent',
    summary: 'Temporary speed improvement in 2029 reversed by 2035 due to induced suburban car influx. Commute delay hits 58 min.',
    summaryTa: '2029ல் கிடைத்த சிறிய பலன் புதிய வாகன வருகையால் 2035ல் வீணானது. தாமதம் 58 நிமிடங்களாக உயர்ந்தது.',
    description: 'Suburban car influx causes severe induced demand traps, worsening gridlock and accelerating particulate emissions.',
    descriptionTa: 'புறநகர் வாகன வருகை தூண்டப்பட்ட நெரிசலை ஏற்படுத்தி, காற்று மாசையும் போக்குவரத்து நெரிசலையும் அதிகப்படுத்தியது.',
    metrics: {
      delay: 58,
      aqi: 172,
      cost: 620,
      risk: 72,
      stress: 76,
    },
    kpis: {
      trafficCongestion: 76,
      pollutionAQI: 172,
      budgetHealth: 54,
      socialAcceptance: 44,
    },
    variableOverrides: {
      'var-highway-expansion': 35,
      'var-veh-density': 680,
    },
    children: ['fork-a1-2050'],
  },
  {
    id: 'fork-b-2035',
    parentId: 'fork-root-2026',
    year: 2035,
    title: 'Branch B: Transit Grid Tipping Point',
    titleTa: 'கிளை B: பொதுப் போக்குவரத்து திருப்புமுனை',
    branchName: 'Transit & Micro-Grid',
    branchNameTa: 'மின்சார போக்குவரத்து',
    strategyName: 'Strategy B',
    status: 'active',
    summary: '62% of commuters shift to electric rapid lines. Highway bottlenecks drop 45%, AQI improves to 74.',
    summaryTa: '62% பயணிகள் மின்சார ரயில் மற்றும் பேருந்திற்கு மாறினர். நெரிசல் 45% குறைந்தது, காற்று தரம் 74 ஆனது.',
    description: '62% modal shift toward clean rapid rail lines stabilizes freeway congestion and triggers air quality recovery.',
    descriptionTa: '62% மக்கள் விரைவு ரயில்களுக்கு மாறியதால் நெடுஞ்சாலை நெரிசல் சீரடைந்து காற்றுத் தரம் மீண்டது.',
    metrics: {
      delay: 28,
      aqi: 74,
      cost: 290,
      risk: 28,
      stress: 28,
    },
    kpis: {
      trafficCongestion: 28,
      pollutionAQI: 74,
      budgetHealth: 82,
      socialAcceptance: 92,
    },
    variableOverrides: {
      'var-transit-cap': 750,
      'var-ev-adoption': 55,
    },
    children: ['fork-b1-2050', 'fork-b2-autonomous-2050'],
  },
  {
    id: 'fork-a1-2050',
    parentId: 'fork-a-2035',
    year: 2050,
    title: 'Outcome A1: Terminal Gridlock & Health Insolvency',
    titleTa: 'விளைவு A1: முழுமையான முடக்கம் & மருத்துவ நெருக்கடி',
    branchName: 'Highway Endgame',
    branchNameTa: 'நெடுஞ்சாலை இறுதி முடிவு',
    strategyName: 'Strategy A Continuation',
    status: 'divergent',
    summary: 'Commute delay reaches 84 min/trip. Annual respiratory burden surpasses $980M. Severe municipal debt.',
    summaryTa: 'பயண தாமதம் 84 நிமிடங்களை எட்டியது. மருத்துவ செலவு $980 மில்லியனாக உயர்ந்தது. கடும் நிதி பற்றாக்குறை.',
    description: 'Terminal gridlock paralysis with 84 minute average trip times, exceeding municipal debt ceilings and public health thresholds.',
    descriptionTa: 'சராசரி 84 நிமிட பயண தாமதத்துடன் மாநகர கட்டமைப்பு முடக்கம். பெரும் மருத்துவ சுமை மற்றும் கடன் நெருக்கடி.',
    metrics: {
      delay: 84,
      aqi: 220,
      cost: 980,
      risk: 88,
      stress: 94,
    },
    kpis: {
      trafficCongestion: 94,
      pollutionAQI: 220,
      budgetHealth: 32,
      socialAcceptance: 25,
    },
    variableOverrides: {
      'var-commute-delay': 84,
      'var-aqi': 220,
    },
    children: [],
  },
  {
    id: 'fork-b1-2050',
    parentId: 'fork-b-2035',
    year: 2050,
    title: 'Outcome B1: Decarbonized 15-Minute Megacity',
    titleTa: 'விளைவு B1: கார்பன் இல்லாத 15-நிமிட பெருநகரம்',
    branchName: '15-Minute City',
    branchNameTa: '15-நிமிட நகர மாதிரி',
    strategyName: 'Strategy B Continuation',
    status: 'active',
    summary: 'Zero tailpipe emissions in metropolitan center. Commute delay stabilized at 22 min. Healthcare savings exceed $480M/yr.',
    summaryTa: 'நகரின் மையத்தில் பூஜ்ய உமிழ்வு. சராசரி தாமதம் 22 நிமிடங்களாக நிலைபெற்றது. ஆண்டுக்கு $480M மருத்துவ சேமிப்பு.',
    description: 'Zero tailpipe emissions, 22-minute average transit times, high social equity, and significant annual healthcare dividend.',
    descriptionTa: 'பூஜ்ய புகை உமிழ்வு, 22 நிமிட சராசரி பயணம், சமத்துவம் மற்றும் ஆண்டுதோறும் மாபெரும் பொது மருத்துவ சேமிப்பு.',
    metrics: {
      delay: 22,
      aqi: 42,
      cost: 160,
      risk: 14,
      stress: 18,
    },
    kpis: {
      trafficCongestion: 18,
      pollutionAQI: 42,
      budgetHealth: 94,
      socialAcceptance: 96,
    },
    variableOverrides: {
      'var-commute-delay': 22,
      'var-aqi': 42,
      'var-ev-adoption': 88,
    },
    children: [],
  },
  {
    id: 'fork-b2-autonomous-2050',
    parentId: 'fork-b-2035',
    year: 2050,
    title: 'Outcome B2: Autonomous Shared Pod Swarms',
    titleTa: 'விளைவு B2: தானியங்கி பகிரப்பட்ட போக்குவரத்து திரள்',
    branchName: 'Autonomous Mesh',
    branchNameTa: 'தானியங்கி இயக்கம்',
    strategyName: 'Strategy B + Autonomous Fleets',
    status: 'active',
    summary: 'Private car ownership drops below 18%. Autonomous micro-shuttles provide on-demand door-to-transit connections.',
    summaryTa: 'சொந்த வாகன பயன்பாடு 18% க்கும் கீழே குறைந்தது. தானியங்கி சிறிய வாகனங்கள் வீடு தோறும் சேவை வழங்குகின்றன.',
    description: 'Shared autonomous electric pod swarms operating on demand, minimizing parking requirements and road footprint.',
    descriptionTa: 'தானியங்கி மின்சார வாகன திரள் தேவைக்கேற்ப செயல்பட்டு சாலை பயன்பாட்டையும் வாகன நிறுத்த இடங்களையும் மிச்சப்படுத்துகிறது.',
    metrics: {
      delay: 16,
      aqi: 35,
      cost: 140,
      risk: 16,
      stress: 12,
    },
    kpis: {
      trafficCongestion: 12,
      pollutionAQI: 35,
      budgetHealth: 91,
      socialAcceptance: 89,
    },
    variableOverrides: {
      'var-commute-delay': 16,
      'var-aqi': 35,
    },
    children: [],
  },
];

export const demoTransportationScenario = demoScenario;
export const demoForkNodes = demoForkTree;

